[package]
name = "hyperstar"
version = "0.1.0"
edition = "2021"
authors = ["Lukas Eschbacher"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/madanifest.html

[dependencies]
num = "0.4.1"
